/control/verbose 2
/run/verbose 2
/testem/phys/addPhysics polarized
/run/printProgress 5000
#
/run/initialize


/polarization/manager/verbose 1
/polarization/volume/set IronCore 0. 0. 1
/polarization/volume/list

/gps/polarization 0. 0. -1.
/gps/particle e-
/gps/energy 20 MeV
/gps/number 100000
/gps/pos/centre 0.0 0.0 -2m

/gps/pos/type Beam
/gps/pos/sigma_r 1  micron
/gps/ang/type beam2d
/gps/ang/sigma_x 10 mrad
/gps/ang/sigma_y 10 mrad
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0




/run/beamOn 1

/gps/polarization 0. 0. 1.

/run/beamOn 1
