#test.mac
/control/verbose 2
/run/verbose 2
/leap/phys/addPhysics polarized

/random/setSeeds 57630758  32767
/run/printProgress 1



#-----------geometry-----------------------------
/leap/det/SetCoreThick 75 mm
/leap/det/SetConvThick 1.75 mm
#/leap/det/update

/run/initialize

/polarization/manager/verbose 1
/polarization/volume/set IronCore 0. 0. 1
/polarization/volume/list


#-----------particle-gunlike-------------------------------
/gps/energy 25 MeV
/gps/number 1000
/gps/particle e-
/gps/pos/centre 0.0 0.0 -2.0 m

#-----------set number of crystals--------------------------
#/leap/det/Setnumberofcrystals nine
#/leap/det/Setnumberofcrystals one

#---------gps-commands-------------------------------------
#simply comment if not needed
/gps/ene/type Mono
/gps/pos/type Point
/gps/direction 0 0 1

#------------------------------------------------------
#run in both polarization directions

/gps/polarization 0. 0. 1

/run/beamOn 1

/gps/polarization 0. 0. -1

/run/beamOn 1
