# Macro file for the initialization of leap sim
# in interactive session
#
# Set some default verbose
#
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Initialize kernel
/run/initialize

/leap/det/Setnumberofcrystals 1 
/leap/det/update
#
/gps/energy 1 GeV
/gps/number 20 #number of electrons in a bunch
/gps/particle e-
/gps/pos/centre 0.0 0.0 -2.0 m


#---------gps-commands-------------------------------------
#simply comment if not needed
#2D-Beam
/gps/pos/type Beam
/gps/pos/sigma_r 0.001  mm
/gps/ang/type beam2d
#/gps/ang/sigma_x 0.01 rad
#/gps/ang/sigma_y 0.01 rad
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0

#Point like source
#/gps/pos/type Point
#/gps/direction 0 0 1
#------------------------------------------------------

/run/beamOn 1 
