executable = /afs/desy.de/group/flc/pool/jenpopp/leap_sims_master/submit_jobs/startCoreThickRun.sh
arguments = $(ProcID) $(corethick)

log = /afs/desy.de/group/flc/pool/jenpopp/leap_sims_master/log/job_$(ProcID).log
output = /afs/desy.de/group/flc/pool/jenpopp/leap_sims_master/out/job_$(ProcID).out
error = /afs/desy.de/group/flc/pool/jenpopp/leap_sims_master/err/job_$(ProcID).err

queue 100 corethick in 50,75,100,125,150,175,200,225,250,275,300
