executable = /afs/desy.de/group/flc/pool/jenpopp/E166_Asy_NurAnalysemagnet/submit_jobs/startCoreThickRun.sh
arguments = $(ProcID) $(corethick)

log = /afs/desy.de/group/flc/pool/jenpopp/E166_Asy_NurAnalysemagnet/log/job_$(ProcID).log
output = /afs/desy.de/group/flc/pool/jenpopp/E166_Asy_NurAnalysemagnet/out/job_$(ProcID).out
error = /afs/desy.de/group/flc/pool/jenpopp/E166_Asy_NurAnalysemagnet/err/job_$(ProcID).err

queue 100 corethick in 50,75,100,125,150,175,200,225,250,275,300
