executable = /afs/desy.de/group/flc/pool/jenpopp/leaps_sims_master/submit_jobs/startErun.sh
arguments = $(ProcID) $(eKin)

log = /afs/desy.de/group/flc/pool/jenpopp/leaps_sims_master/log/job_$(ProcID).log
output = /afs/desy.de/group/flc/pool/jenpopp/leaps_sims_master/out/job_$(ProcID).out
error = /afs/desy.de/group/flc/pool/jenpopp/leaps_sims_master/err/job_$(ProcID).err

queue 100 eKin in 1,2,3,5,7,10,15,20,30,40,50,60,80,100,120
