/control/verbose 2
/run/verbose 2
/leap/phys/addPhysics polarized


/run/printProgress 5000

/run/initialize

#-----------geometry-----------------------------
/leap/det/SetCoreThick 300 mm
/leap/det/SetConvThick 1.75 mm
/leap/det/update

/polarization/manager/verbose 1
/polarization/volume/set IronCore 0. 0. 1
/polarization/volume/list

#-----------particle-gunlike-------------------------------
/gps/energy 20 MeV
/gps/number 100000 #number of electrons in a bunch
/gps/particle e-
/gps/pos/centre 0.0 0.0 -2.0m

#---------gps-commands-------------------------------------
#simply comment if not needed

/gps/pos/type Beam
/gps/pos/sigma_r 1  micron
/gps/ang/type beam2d
/gps/ang/sigma_x 10 mrad
/gps/ang/sigma_y 10 mrad
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0

#------------------------------------------------------
#run in both polarization directions

/gps/polarization 0. 0. +1.

/run/beamOn 1

/gps/polarization 0. 0. -1.

/run/beamOn 1
