/control/verbose 2
/run/verbose 2
/leap/phys/addPhysics polarized


/run/printProgress 5000

/run/initialize

#-----------geometry-----------------------------
/leap/det/SetCoreThick 300 mm
/leap/det/SetConvThick 1.75 mm
/leap/det/update

/polarization/manager/verbose 1
/polarization/volume/set Magnet 0. 0. 1
/polarization/volume/list

#-----------energy-------------------------------
/gun/energy 20 MeV
/gun/number 10000
#------------------------------------------------------
/gun/polarization 0. 0. +1.

/run/beamOn 1

/gun/polarization 0. 0. -1.

/run/beamOn 1
